/**
 * Cancellation policies acceptance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CancellationPoliciesAcceptance) {
      root.CancellationPoliciesAcceptance = {};
    }
    root.CancellationPoliciesAcceptance.PolicyInfo = factory(root.CancellationPoliciesAcceptance.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PolicyInfo model module.
   * @module model/PolicyInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PolicyInfo</code>.
   * @alias module:model/PolicyInfo
   * @class
   * @param quotationId {String} 
   * @param basketItemId {String} 
   * @param rph {Number} 
   * @param message {String} 
   * @param originalMessage {String} 
   */
  var exports = function(quotationId, basketItemId, rph, message, originalMessage) {
    var _this = this;


    _this['quotationId'] = quotationId;

    _this['basketItemId'] = basketItemId;
    _this['rph'] = rph;



    _this['message'] = message;
    _this['originalMessage'] = originalMessage;


  };

  /**
   * Constructs a <code>PolicyInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PolicyInfo} obj Optional instance to populate.
   * @return {module:model/PolicyInfo} The populated <code>PolicyInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('quotationId')) {
        obj['quotationId'] = ApiClient.convertToType(data['quotationId'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
      if (data.hasOwnProperty('basketItemId')) {
        obj['basketItemId'] = ApiClient.convertToType(data['basketItemId'], 'String');
      }
      if (data.hasOwnProperty('rph')) {
        obj['rph'] = ApiClient.convertToType(data['rph'], 'Number');
      }
      if (data.hasOwnProperty('hasErrors')) {
        obj['hasErrors'] = ApiClient.convertToType(data['hasErrors'], 'Boolean');
      }
      if (data.hasOwnProperty('isAccepted')) {
        obj['isAccepted'] = ApiClient.convertToType(data['isAccepted'], 'Boolean');
      }
      if (data.hasOwnProperty('isRefundable')) {
        obj['isRefundable'] = ApiClient.convertToType(data['isRefundable'], 'Boolean');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('originalMessage')) {
        obj['originalMessage'] = ApiClient.convertToType(data['originalMessage'], 'String');
      }
      if (data.hasOwnProperty('errorMessage')) {
        obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
      }
      if (data.hasOwnProperty('upsertError')) {
        obj['upsertError'] = ApiClient.convertToType(data['upsertError'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} quotationId
   */
  exports.prototype['quotationId'] = undefined;
  /**
   * @member {String} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {String} basketItemId
   */
  exports.prototype['basketItemId'] = undefined;
  /**
   * @member {Number} rph
   */
  exports.prototype['rph'] = undefined;
  /**
   * @member {Boolean} hasErrors
   */
  exports.prototype['hasErrors'] = undefined;
  /**
   * @member {Boolean} isAccepted
   */
  exports.prototype['isAccepted'] = undefined;
  /**
   * @member {Boolean} isRefundable
   */
  exports.prototype['isRefundable'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {String} originalMessage
   */
  exports.prototype['originalMessage'] = undefined;
  /**
   * @member {String} errorMessage
   */
  exports.prototype['errorMessage'] = undefined;
  /**
   * @member {Boolean} upsertError
   */
  exports.prototype['upsertError'] = undefined;



  return exports;
}));


