/**
 * Cancellation policies acceptance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CancellationPoliciesAcceptance);
  }
}(this, function(expect, CancellationPoliciesAcceptance) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CancellationPoliciesAcceptance.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('acceptedAllCancellationPolicies', function() {
      it('should call acceptedAllCancellationPolicies successfully', function(done) {
        //uncomment below and update the code to test acceptedAllCancellationPolicies
        //instance.acceptedAllCancellationPolicies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createCancellationPolicyEntries', function() {
      it('should call createCancellationPolicyEntries successfully', function(done) {
        //uncomment below and update the code to test createCancellationPolicyEntries
        //instance.createCancellationPolicyEntries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAllCancellationPolicyEntry', function() {
      it('should call deleteAllCancellationPolicyEntry successfully', function(done) {
        //uncomment below and update the code to test deleteAllCancellationPolicyEntry
        //instance.deleteAllCancellationPolicyEntry(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCancellationPolicyByQuotationIdAndItemId', function() {
      it('should call deleteCancellationPolicyByQuotationIdAndItemId successfully', function(done) {
        //uncomment below and update the code to test deleteCancellationPolicyByQuotationIdAndItemId
        //instance.deleteCancellationPolicyByQuotationIdAndItemId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCancellationPolicyByQuotationIdAndItemIdAndRph', function() {
      it('should call deleteCancellationPolicyByQuotationIdAndItemIdAndRph successfully', function(done) {
        //uncomment below and update the code to test deleteCancellationPolicyByQuotationIdAndItemIdAndRph
        //instance.deleteCancellationPolicyByQuotationIdAndItemIdAndRph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllCancellationPolicyEntryByQuotationId', function() {
      it('should call getAllCancellationPolicyEntryByQuotationId successfully', function(done) {
        //uncomment below and update the code to test getAllCancellationPolicyEntryByQuotationId
        //instance.getAllCancellationPolicyEntryByQuotationId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCancellationPolicyEntryByQuotationIdAndItemId', function() {
      it('should call getCancellationPolicyEntryByQuotationIdAndItemId successfully', function(done) {
        //uncomment below and update the code to test getCancellationPolicyEntryByQuotationIdAndItemId
        //instance.getCancellationPolicyEntryByQuotationIdAndItemId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
